apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-generator
  labels:
    app: template-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-generator
  template:
    metadata:
      labels:
        app: template-generator
    spec:
      containers:
      - name: template-generator-client
        image: eu.gcr.io/template-generator-230500/template-generator-client:${TAG}
        ports:
        - containerPort: 80
      - name: template-generator-server
        image: eu.gcr.io/template-generator-230500/template-generator-server:${TAG}
        ports:
        - containerPort: 3000